import React from 'react';
import ReactDOM from 'react-dom';
import Blog from './Blog';
import WelcomeModal from './WelcomeModal';
//import './style.css'; //При добавлении этой строки при сборке проекта ошибка "ReferenceError: window is not defined"

const App = (props) =>{
    const posts = [
        {author:'Ann', title: 'Lorem1', postbody: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi esse voluptatum quam fugit quasi eos veniam, voluptatibus eaque doloremque dolorem voluptas, quas beatae nam, cum aspernatur dolorum exercitationem praesentium, delectus eveniet. Debitis dignissimos aperiam perspiciatis quo, ducimus modi sit sapiente nemo, molestias omnis excepturi ipsum accusantium esse distinctio at harum deserunt provident quis inventore commodi cum rem. Consectetur itaque totam blanditiis illum, culpa, rem ratione, aspernatur optio sit quos dicta autem quae explicabo cumque maiores laboriosam. Perferendis, hic illum dolorem aperiam odio impedit quia odit delectus enim at fuga iusto. Unde odio facilis omnis iusto soluta saepe nam ratione. Consectetur aperiam dolorem ullam facilis maxime quaerat provident, voluptas aliquam consequuntur soluta fugit beatae ducimus nostrum praesentium sequi illo nam culpa minima velit itaque deleniti numquam magni. Neque sunt atque, itaque accusantium, illo, quis in doloribus vero expedita commodi repellendus sit ipsum possimus saepe reprehenderit. Velit quis, ex itaque, explicabo harum molestiae, iusto tempore ipsam quam sed iure magnam quia quibusdam vitae numquam a ducimus doloremque ad totam deserunt. Quidem quasi debitis laborum modi animi fugit minus, non minima. Corporis nam eaque temporibus quas sequi, debitis cum omnis quos placeat quaerat doloribus earum, harum, similique cumque iusto, iste totam nostrum nisi!', postdate: 'March 27, 2019'},
        {author:'Andrew', title: 'Lorem2', postbody: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis perspiciatis quae aliquam eaque odio impedit quas, voluptas qui itaque sapiente quos tenetur veniam sequi, odit ducimus suscipit blanditiis error, obcaecati numquam vero hic inventore. Sequi consectetur libero recusandae temporibus nisi ipsa facilis excepturi debitis nostrum vitae, cumque eius deserunt odit necessitatibus fugiat ea officiis quae esse cum sunt illo? Dolorum asperiores laudantium veritatis placeat, eligendi dolor nulla saepe. Saepe possimus incidunt quae aspernatur quidem atque sint consequuntur laboriosam, cumque illum ea ullam libero at fugit, ipsa fugiat minima ratione a consequatur, sit autem! Architecto est iure praesentium eum doloribus dolores voluptates eos aperiam iusto nam, dicta qui, ab quod rerum nesciunt repellendus nemo, cupiditate voluptatem! Quam, minus? Voluptate accusamus adipisci, necessitatibus reiciendis fuga deleniti ab tempore optio iure, accusantium veritatis laboriosam, in impedit odio. Impedit a esse quas at commodi. Maiores deleniti ipsam, sapiente reprehenderit laboriosam unde, odit voluptatem. Commodi dicta atque et voluptas, iste rem ab illum labore similique eius voluptatum nesciunt voluptatibus eveniet quaerat dignissimos perferendis aspernatur vitae nemo animi, quis illo earum ullam eos sint pariatur. Architecto.', postdate: 'March 24, 2019'},
        {author:'Robert', title: 'Lorem3', postbody: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni nisi ullam doloribus nulla quibusdam. Debitis explicabo alias eos saepe dignissimos, laboriosam laborum libero, hic ex quasi quisquam sequi voluptate magnam dolorem, accusamus sapiente amet tenetur fugit maiores mollitia incidunt ratione minima minus quaerat, non. Ad tempora deserunt voluptatum, perferendis quos nostrum, ex repudiandae dolorum, ratione assumenda, optio. Reprehenderit suscipit possimus officiis culpa nemo aut illum atque officia illo ipsam quidem architecto repellendus nesciunt, dolores ullam quod. Fugit voluptatum consequuntur perferendis impedit quod laboriosam, in molestias, numquam, quae nemo, eos tenetur. Ad laborum, harum sit porro voluptates. Suscipit doloribus necessitatibus, incidunt sint architecto soluta, fuga. Eveniet quas consequuntur blanditiis eligendi porro temporibus velit alias, officia magni expedita? Laboriosam accusantium velit unde ex inventore molestias incidunt laudantium, odio sequi error vitae at aliquam, aperiam soluta, quidem possimus quaerat suscipit provident corporis veniam ullam dolorum iusto, sint. Facere doloribus molestias consectetur eius asperiores.', postdate: 'April 02, 2019'},
        {author:'Nataly', title: 'Lorem4', postbody: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed corrupti atque exercitationem, doloremque odio ipsum, optio nemo! Perferendis dolores minus numquam totam aliquid laudantium, voluptatibus officiis repellendus nesciunt sapiente non nisi porro quae, aspernatur sed.', postdate: 'December 12, 2018'},
        {author:'Tom', title: 'Lorem5', postbody: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium quae inventore libero repellat, perferendis illum laborum assumenda facilis consequatur, vel unde id aperiam ipsa maiores numquam ratione rem? Cumque provident autem, magnam quibusdam possimus voluptatum et porro. Aliquid odio alias illum, ipsum quas doloribus dolores consequuntur vero repellendus, rem similique modi dicta laborum fugiat velit est omnis labore incidunt itaque sunt mollitia. Omnis iste doloribus aspernatur laboriosam illo mollitia voluptate nemo ullam asperiores qui! Odio soluta dicta, animi amet quam. Aperiam nam labore itaque reiciendis voluptates eligendi amet ex fugiat officia pariatur eius laudantium obcaecati qui ipsum totam animi cumque ratione possimus tempore autem, porro reprehenderit numquam placeat. Eum a saepe natus, veritatis repellendus est beatae expedita numquam laudantium, fugit aspernatur debitis dolorem fugiat sequi reprehenderit neque. Quo obcaecati odit fugiat, sint accusamus nihil ducimus tempore ullam sapiente voluptates unde eveniet, corporis voluptatibus quod, distinctio consequuntur? Expedita perferendis magnam optio reiciendis earum sapiente omnis repudiandae officiis libero eligendi fugit quod, laudantium, alias commodi doloremque. Est sunt laborum odio illum debitis neque nisi ad pariatur eligendi at voluptas, modi, animi quasi iste, iure dolor excepturi? Cupiditate, praesentium repellat nulla delectus natus hic dignissimos placeat, officia temporibus laboriosam dolores debitis! Illum harum quaerat, cupiditate est nihil ex ipsam quod dolores, aperiam at nesciunt iste recusandae nulla repellat impedit suscipit expedita et.', postdate: 'February 16, 2018'}
    ];
    return(
        <>
            <WelcomeModal/>
            <Blog posts={posts}/>                    
        </>
    );
}

ReactDOM.render(<App/>, document.querySelector('#root'));


